dockerui:
    container_name: tm351-dockerui
    image: uifd/ui-for-docker
    ports:
        - "35183:9000"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
  
#Seems we can't share the mongo data folder with host, on mac at least?
devmongodata:
    container_name: tm351-devmongodata
    command: echo mongodb_created
    #Share same layers as the container we want to link to?
    image: mongo:3.0.7
    volumes: 
        - /data/db

mongodb:
    container_name: tm351-mongodb
    image: mongo:3.0.7
    ports:
        - "27017:27017"
    #Ideally we should be able to mount this against a host directory
    #volumes:
    #  - ./db/mongo/:/data/db
    volumes_from:
        - devmongodata
    command: --smallfiles

mongodb-seed:
    container_name: tm351-mongodb-seed
    image: psychemedia/ou-tm351-mongodb-simple-seed
    links:
        - mongodb

#Seems we can't share the postgres data folder with host, on mac at least?
# eg https://github.com/boot2docker/boot2docker/issues/581#issuecomment-70596122
devpostgresdata:
    container_name: tm351-devpostgresdata
    command: echo created
    image: busybox
    volumes: 
        - /var/lib/postgresql/data
        #I think this is how we'd mount the data container against a host directory
        #    - ./db/postgres/:/var/lib/postgresql/data
 
postgres:
    container_name: tm351-postgres
    environment:
        - POSTGRES_PASSWORD=PGPass
    image: psychemedia/ou-tm351-postgres
    ports:
        - "5432:5432"
    #Ideally we should be able to mount this - or the data container - 
    # against a host directory
    #volumes:
    #    - ./db/postgres/:/var/lib/postgresql/data
    volumes_from:
        - devpostgresdata

openrefine:
    container_name: tm351-openrefine
    image: psychemedia/ou-tm351-openrefine
    ports:
        - "35181:3333"
    volumes:
        - ./openrefine_projects/:/mnt/refine
    privileged: true
    
notebook:
    container_name: tm351-notebook
    #build: ./tm351_scipystacknserver
    image: psychemedia/ou-tm351-pystack
    ports:
        - "35180:8888"
    volumes:
        - ./notebooks/:/notebooks/
    links:
        - postgres:postgres
        - mongodb:mongodb
        - openrefine:openrefine
    privileged: true
